### ISSUE TITLE
Add structure for the catch-api repo

### ISSUE THREAD

**Issue by admin-datr-tech** [datr-tech/catch-api#1]
## Overview

The structure should include:
- TypeScript setup: tsconfig.json
- ESLint setup
- Prettier setup
- FTA setup
- .gitignore
- README (empty except for the title and a warning about ongoing development)
- ./dist, ./src and ./test dirs
- package.json

## Acceptance criteria

Ability to successfully perform the following:
- npm run lint
- npm run format
- npm run test (though no tests have been added)

**Comment by j-alderson-strachan** [comment]
To simplify the process of pushing the initial commit, it was pushed directly to the remote master branch.
