### ISSUE TITLE
Add an OpenAPI `spec` route

### ISSUE THREAD

**Issue by admin-datr-tech** [datr-tech/catch-api#3]
## Overview

- Create a `spec` route, which will return the OpenAPI spec
- Create an initial draft of the OpenAPI spec for the catch-api

## Acceptance criteria

- The unit tests associated with the spec route should provide 100% coverage

**Comment by j-alderson-strachan** [comment]
An initial version of the OpenAPI schema has been added. It can be accessed via:

- /api/v1/docs
- /api/schema/{schemaVersion}

However, there schema will require further detail in order to handle SERP responses
